name: ci/cd-pipeline
on:
  push:
    branches: [ develop ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to QA
        uses: appleboy/ssh-action@master
        with:
          username: test
          host: 127.0.0.1
          password: test
          script: |
            cd /
            cd /home/jars/schools-front-end
            git stash -u
            git pull https://flanchoooo:${{secrets.TOKEN}}@github.com/famethe-technologies/schools-front-end develop
            docker stop schools-front-ends
            docker rm schools-front-ends
            docker rmi schools-front-ends
            docker build -t schools-front-ends .
            docker run -d -p 1111:8080 --name=schools-front-ends --restart=always schools-front-ends


